INSERT INTO pokemon_types(id, is_real)
VALUES ('bug', true),
       ('dark', true),
       ('dragon', true),
       ('electric', true),
       ('fairy', true),
       ('fighting', true),
       ('fire', true),
       ('flying', true),
       ('ghost', true),
       ('grass', true),
       ('ground', true),
       ('ice', true),
       ('normal', true),
       ('poison', true),
       ('psychic', true),
       ('rock', true),
       ('steel', true),
       ('water', true),
       ('none', false);
